baseURL = "https://sarah.engineer/"
languageCode = "en-us"
title = "sarah . engineer"
theme = "hyde"
enableEmoji = true
relativeURLs = true

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/cgsdev0"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/cgsdev"}
  ]

[params]
  themeColor = "theme-base-0d"
  description = "full-stack software engineer • game designer"

[mediaTypes]
[mediaTypes."text/markdown"]
suffixes = ["md"]

[outputFormats]
  [outputFormats.MD]
    baseName = 'index'
    isPlainText = true
    mediaType = 'text/markdown'

[outputs]
  page = ['HTML', 'MD']
  section = ['HTML', 'MD']
  term = ['HTML', 'MD']
  taxonomy = ['HTML', 'MD']
